### ISSUE TITLE
My first issue ;)

### ISSUE THREAD

**Issue by mcferson** [Furtif/RocketBot#15]
Hi there.
Thanks a lot to keep this alive.
However i got an issue at launch. Here the log :

> [13:32:55] Connexion via Google
[13:32:56] Connecté en tant que xxxxxxxxx
[13:32:56] Destination : 48.8837820680614,2.23878035309809
[13:32:57] ====== Classement par PC ======
[13:32:57] ====== Classement par IV ======
[13:32:57] Incubation en cours, 1.14km restant
[13:32:57] Incubation en cours, 5.00km restant
[13:32:57] Aucun oeuf de disponible
[13:32:57] Pokédex (151) : Rencontré 135 | Capturé 130
[13:32:57] Pokemon Servers might be offline / unstable. Trying again...
[13:32:58] Error: System.InvalidOperationException: La séquence ne contient aucun élément.
   à System.Linq.Enumerable.First[TSource](IEnumerable'1 source)
   à PokemonGo.RocketBot.Logic.Utils.RouteOptimizeUtil.FindNn(IEnumerable'1 pokeStops, Double cLatitude, Double cLongitude) dans C:\Users\Brian\Documents\Visual Studio 2015\Projects\RocketBot\PokemonGo.RocketBot.Logic\Utils\RouteOptimizeUtil.cs:ligne 107
   à PokemonGo.RocketBot.Logic.Utils.RouteOptimizeUtil.Optimize(FortData[] pokeStops, Double lat, Double lng) dans C:\Users\Brian\Documents\Visual Studio 2015\Projects\RocketBot\PokemonGo.RocketBot.Logic\Utils\RouteOptimizeUtil.cs:ligne 16
   à PokemonGo.RocketBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__3.MoveNext() dans C:\Users\Brian\Documents\Visual Studio 2015\Projects\RocketBot\PokemonGo.RocketBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 58
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à PokemonGo.RocketBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans C:\Users\Brian\Documents\Visual Studio 2015\Projects\RocketBot\PokemonGo.RocketBot.Logic\State\FarmState.cs:ligne 66
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à PokemonGo.RocketBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\Brian\Documents\Visual Studio 2015\Projects\RocketBot\PokemonGo.RocketBot.Logic\State\StateMachine.cs:ligne 56

**Comment by Furtif** [comment]
?? On dirait que vous manque les packages nuget...

**Comment by mcferson** [comment]
ça devrait être compilé avec la solution, normalement.
Vous avez testé sur un autre poste que votre poste de dev ?

**Comment by Furtif** [comment]
sinon j'ai un pull chez le createur il suffit le le merger mais sa fait un moment que eux ne bougent pas :s:s

**Comment by Furtif** [comment]
je creer un release beta https://github.com/Furtif/RocketBot/releases, la dev de base (https://github.com/TheUnnameOrganization/RocketBot) este encore a lapi 0.35 pour sa que tas ce erreur, si vous utilisez ma solution l'api est la derniere ou configurable.

**Comment by mcferson** [comment]
Justement, j'utilise votre solution.

**Comment by Furtif** [comment]
Ma version ne utilise plus ces fichiers

PokemonGo.RocketBot.Logic
POGOProtos... dans votre log je vois ces fichiers mentionnées essayez de reclonner le repo d'ici pas de TheUnname...  https://github.com/Furtif/RocketBot/

**Comment by mcferson** [comment]
i'm a bit lost. i use your version while i got this error.

**Comment by Furtif** [comment]
si vous modifiez le source code et vous voulez le partagez faites une requette pull das ma branche "beta"

**Comment by Furtif** [comment]
"P.S. : did not see that my logs are in french ! lol ! I wonder why you answer me in french."

Je suis français sa me arrange répondre en français ^^

**Comment by mcferson** [comment]
aaah ok.
Bon, je viens de me rendre compte d'un truc : le lien de DL pointe vers RocketBot.
En téléchargeant la beta, j'ai bien NecroBot. Donc ce que j'utilisais, c'était la RocketBot et pas la votre.

**Comment by mcferson** [comment]
je vais voir ce que ça donne, du coup

**Comment by Furtif** [comment]
👍

**Comment by mcferson** [comment]
bon...
le contenu du détail du JIT :

> Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'PoGo.NecroBot.Logic, Version=1.0.0.42, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Tentative de chargement d’un programme de format incorrect.
Nom de fichier : 'PoGo.NecroBot.Logic, Version=1.0.0.42, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Impossible de charger le fichier ou l'assembly 'PoGo.NecroBot.Logic, Version=1.0.0.42, Culture=neutral, PublicKeyToken=null'. Cet assembly a été compilé pour un autre processeur.
   à System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
   à System.Reflection.Assembly.Load(Byte[] rawAssembly)
   à Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   à Costura.AssemblyLoader.ResolveAssembly(String assemblyName)
   à Costura.AssemblyLoader.<Attach>b__0(Object s, ResolveEventArgs e)
   à System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   à NecroBot2.Forms.MainForm.InitializeBot()
   à NecroBot2.Forms.MainForm.MainForm_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NecroBot2
    Version de l'assembly : 2.4.1.1
    Version Win32 : 2.4.1.1
    CodeBase : file:///D:/GAMES/Necrobot/NecroBot2.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GMap.NET.Core
    Version de l'assembly : 1.7.0.0
    Version Win32 : 2.4.1.1
    CodeBase : file:///D:/GAMES/Necrobot/NecroBot2.exe
----------------------------------------
GMap.NET.WindowsForms
    Version de l'assembly : 1.7.0.0
    Version Win32 : 2.4.1.1
    CodeBase : file:///D:/GAMES/Necrobot/NecroBot2.exe
----------------------------------------
ObjectListView
    Version de l'assembly : 2.9.1.1072
    Version Win32 : 2.4.1.1
    CodeBase : file:///D:/GAMES/Necrobot/NecroBot2.exe
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.SQLite
    Version de l'assembly : 1.0.84.0
    Version Win32 : 1.0.84.0
    CodeBase : file:///C:/Users/Olivier%20Buisson/AppData/Local/GMap.NET/DllCache/SQLite_v84_NET4_x86/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by Furtif** [comment]
PoGo.NecroBot.Logic depends de POGOProtos.NetStandard1 2.4.1 et PokemonGo.RocketAPI (feroxrev) faudra voir si tas clonner  le sousmodule ..... 
sinon faut le clonner https://github.com/Furtif/FeroxRev/tree/bc578a37fbd9728d0c12d557ada2842c2a39e856

**Comment by Furtif** [comment]
se sont des lib a eviter de modifier 

PoGo.NecroBot.Logic
PokemonGo.RocketAPI

**Comment by mcferson** [comment]
Ca devient compliqué là. tu as une procédure pour monsieur tout le monde, pour installer l'appli, avec les liens de ce qu'il faut ?
J'ai pas réinstallé mon VS, je suis une grosse feignasse.

**Comment by Furtif** [comment]
Avez vous d'autres questions?

**Comment by mcferson** [comment]
Je viens de récupérer la toute dernière release.
C'est obligé de passer par une API Key payante ? Ca peut pas être remplacé par autre chose ?

**Comment by mcferson** [comment]
ouai ouai mais non :D
Je laisse tomber. Pour moi c'est mort. je vais pas payer 4$ par mois.
Prions pour qu'un groupe hack l'API et soit moins malhonnête.
Bon en tout cas, bien joué de reprendre en main ce bot et bonne continuation.

**Comment by Furtif** [comment]
Merci, bon moi par le moment je pas acheter de api je utilise la legacy jusque présent sa se passe bien.

**Comment by mcferson** [comment]
ah oui ?
Je veux bien tenter le coup, mais je vais grognon si je me fais bannir :D

**Comment by Furtif** [comment]
bah creez un compte pour tester avant de utiliser la votre principal... sa evite de grodnon ^^

**Comment by mcferson** [comment]
j'ai une question : comment configurer le config.json, pour la résolution des captcha ?

**Comment by Furtif** [comment]
en general google chrome et la config par defaut sa ouvre la fenetre captcha (manuelement) pour la config auto faudra voir du cote wiki de necrobot,

**Comment by mcferson** [comment]
moi ça n'ouvre rien, ça me fait une erreur. Je suppose qu'il faut avoir chrome installé ?
Perso j'utilise Opera (moteur chrome)

**Comment by mcferson** [comment]
rien sur le wiki.

**Comment by mcferson** [comment]
ah oui, faut installer chrome :)

**Comment by Furtif** [comment]
oui avec chrome sa fonctionne car l'application utilise un composant chrome

**Comment by Furtif** [comment]
@mcferson je ferme se issue veuillez vous rendre ici pour la suite et je désactive les issues dans ce repos
https://github.com/TheUnnamedOrganisation/RocketBot/issues
